### ISSUE TITLE
Fix `brew` issue in GHA

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-rnp#23]
https://github.com/rnpgp/homebrew-rnp/runs/3028325747

```
##[group]Run brew bottle --json --force-core-tap ${FORMULA}
[36;1mbrew bottle --json --force-core-tap ${FORMULA}[0m
[36;1msource ci/read_bottle_metadata.sh[0m
[36;1mci/build_bintray_descriptor.rb[0m
shell: /bin/bash -e {0}
env:
  FORMULA: ./Formula/rnp.rb
  OPTS: 
  BINTRAY_PACKAGE: rnp
  BINTRAY_DESCRIPTOR_FILENAME: bintray_descriptor.json
##[endgroup]
[31mError:[0m undefined method `path' for nil:NilClass
[34m==>[0m [1mDetermining rnp bottle rebuild...[0m
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:25:in `initialize'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:314:in `new'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:314:in `bottle_formula'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:105:in `block in bottle'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `bottle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
##[error]Process completed with exit code 1.
```

**Comment by ronaldtse** [comment]
```
Error: undefined method `path' for nil:NilClass
13
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:25:in `initialize'
14
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:314:in `new'
15
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:314:in `bottle_formula'
16
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:105:in `block in bottle'
17
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `each'
18
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `bottle'
19
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
20
```
